### ISSUE TITLE
[1.12] Ore Dictionary stuff changed (recipes are broken)

### ISSUE THREAD

**Issue by xbony2** [xbony2/HuesoDeWiki#25]
~~Stuff missing (tested with 2452).~~

To be more specific, ore dictionary entries registered under more than one name (like how an entire group might be both wool and blockWool) seem to be the issue.

**Comment by Lykrast** [comment]
Adding that 1.5.0 seems to consistently miss `blockGlass`. This can be tested with Environmental Tech at least.
