### ISSUE TITLE
Misreporting durability of tools by +1

### ISSUE THREAD

**Issue by xenoflot** [xbony2/HuesoDeWiki#31]
e.g. If a tool's durability is 350, Hueso will put 351 on the clipboard.
Verified with tools from 3 mods.

forge 14.23.1.2560
hdw 1.3.2a

**Comment by xbony2** [comment]
@xenoflot dumping Iron Shovel gives the durability of 251. According to the MC Wiki, Iron tools have 251 uses. Are the number of uses different from durability?

**Comment by xenoflot** [comment]
A wooden shovel has a metadata of 0/59 and gave me 60 pieces of dirt. 

Iron' Shovel metadata shows 0/250.
Mekanism tools JEI tooltip report the number of hitpoints which is that metadata value.

I guess both are correct in their own way. Given the number of inconsistencies in Mekanism, I'm happy to ignore it :D

**Comment by xbony2** [comment]
I'd count the durability of the Wooden Shovel as 60. Don't really know.

**Comment by elifoster** [comment]
Seems correct to me.
