### ISSUE TITLE
Controls category has wrong name

### ISSUE THREAD

**Issue by elifoster** [xbony2/HuesoDeWiki#37]
In the controls menu, it's listed as "HuesosDeWiki" instead of "HuesoDeWiki"

**Comment by xbony2** [comment]
ты хуисос

**Comment by elifoster** [comment]
I wish

**Comment by Rusy233-ms** [comment]
?

**Comment by xbony2** [comment]
@Rusy233-ms the mod's name used to be "huesos" which was kind of a transliteration of хуесос apparently. Two Russians complained and I changed the mod name.
