### ISSUE TITLE
More missing infobox parameters

### ISSUE THREAD

**Issue by Hubry** [xbony2/HuesoDeWiki#39]
- [x] `enchantability`
- [x] `mininglevel` - Basically only for pickaxes
- [x] `miningspeed`
- [x] `oredictname` - Item's ore dictionary tags
- [x] `effects` - Potion effects of food/potion (not a big priority).
- [x] `tentity` (type for `type`, rather important)

**Comment by elifoster** [comment]
I'm not sure how effects could be done, since typically when you add potion effects to food you do so through one of the onEaten hooks

**Comment by Hubry** [comment]
Well, I am not sure either, didn't look at my dev env, but I noticed [this line](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/ItemManaCookie.java#L35) in one of Botania's items, which just extends `ItemFood`. As I said, it's not important and probably won't get used much, but if it's possible then why not? This mod won't catch everything every time anyways.

**Comment by elifoster** [comment]
Oh yeah, I forgot about that.
