### ISSUE TITLE
[Suggestion] Add option for dumpstructure to wrap the multiblock in a collapsed table

### ISSUE THREAD

**Issue by Lykrast** [xbony2/HuesoDeWiki#59]
Like it is done on the [Astral Sorcery](https://ftb.gamepedia.com/Attunement_Altar) and [Environmental Tech](https://ftb.gamepedia.com/Solar_Array_Controller) pages to hide massive structures, having an optional parameter to the `dumpstructure` command to wrap the multiblock template in a collapsed table like so:

```
{| class="wikitable mw-collapsible mw-collapsed"
|-
! Structure
|-
| {{Cg/Multiblock/Alt
.................
}}
|}
```

Would be a nice addition.

**Comment by xbony2** [comment]
I can't assign @Hubry to this since he doesn't have push access but consider him assigned.
