### ISSUE TITLE
Automatic thing support for the first sentence.

### ISSUE THREAD

**Issue by xbony2** [xbony2/HuesoDeWiki#7]
`
The '''Something''' is a THING added by [[Some Mod]].
`

"Food" and "weapon" come as potential things to be supported.

**Comment by elifoster** [comment]
It would probably be a good idea to use the type parameter stuff for this, imo.

**Comment by xbony2** [comment]
They don't correspond perfectly, like I'd rather have `The '''Bronze''' Helmet is a helmet armor added by [[IC2]].` We'll see.
