### ISSUE TITLE
Port to 1.16.2

### ISSUE THREAD

**Issue by xbony2** [xbony2/HuesoDeWiki#78]
I know, 1.16.1->1.16.2. But for some reason, specifying a license in the mod toml is now required, or was required but may be in the future. I don't know, Forge is wildin'.

**Comment by Hubry** [comment]
It might not even work on 1.16.2 with a license specified. This version changed a lot more than you might expect and tons of people are surprised Mojang dared to call it a minor patch.

And why is Hueso not using an open source license, anyways? I wish it was MIT or LGPL or something else tbh.

**Comment by xbony2** [comment]
Sorry sir I don't think you've read the license... you are not given permission to complain about the product... see you in court soon.

**Comment by Hubry** [comment]
sorry sir but complaining about the product explicitly falls under fair use as reviewing purposes

**Comment by xbony2** [comment]
sorry sir but nowhere in the license does it say you can use the product... if you reviewed it you must have used it... the police are coming to your house as we speak...

**Comment by Hubry** [comment]
sorry sir but you have agreed to people using your product when you put it up on this weird website called curseforge and people can even put it in those "modpacks" if they want to because you put it there

**Comment by xbony2** [comment]
no sir i did not! an imposter put it on curseforge, probably you! you and your imposter friends (probably associated with Rusy) are headed to prison!
