### ISSUE TITLE
Does not load on 1.18.1

### ISSUE THREAD

**Issue by sscards55** [xbony2/HuesoDeWiki#83]
[crash-2022-01-01_07.20.48-fml.txt](https://github.com/xbony2/HuesoDeWiki/files/7797161/crash-2022-01-01_07.20.48-fml.txt)

**Comment by xbony2** [comment]
I think this is unique to this mod, and not my other mods, at least. Will investigate soon.

**Comment by xbony2** [comment]
Loads in dev environment, obviously...

**Comment by Hubry** [comment]
In prod it's `m_44054_`.

I'd recommend moving to accessor mixins over Forge's reflection helper at this point :P

**Comment by xbony2** [comment]
Well, I know what the problem is. Real PITA to fix (and I'm not sure why `ObfuscationReflectionHelper` doesn't work as expected). I'll try to do fix it some later (unless Hubry wants to step in).

This is probably a problem with 1.17 too, but would have to test.

**Comment by Hubry** [comment]
> I'm not sure why ObfuscationReflectionHelper doesn't work as expected

It takes unmapped names, and leaves them as-is if unrecognized. You passed in a mapped name, so it did nothing to it.

**Comment by xbony2** [comment]
I'm a dumbass then, who switched from an outdated unmapped name to a mapped name for some reason.

**Comment by Hubry** [comment]
Automated remapping would do that, funnily enough. That's why every time Forge intentionally uses an unmapped name it does it like `"th" + "is"`.

**Comment by xbony2** [comment]
I don't see why Mojang still has obfuscated code if they give out the mappings anyway. Anyway, it _should_ be good now. Try it out.
