### ISSUE TITLE
Game crashes on button press.

### ISSUE THREAD

**Issue by sscards55** [xbony2/HuesoDeWiki#84]
[crash-2022-01-02_07.56.29-client.txt](https://github.com/xbony2/HuesoDeWiki/files/7798326/crash-2022-01-02_07.56.29-client.txt)

**Comment by xbony2** [comment]
Of course, managed to replicate it in MultiMC, but not in unIntelliJ.

**Comment by xbony2** [comment]
It's an ObfuscationReflectionHelper problem again.
